context:
  version: "0.0.15"

package:
  name: khiops-driver-s3
  version: ${{ version }}

source:
  url: https://github.com/KhiopsML/khiopsdriver-s3/archive/refs/tags/${{ version }}.tar.gz
  sha256: 7717c626b2ee8e3c52af3b5e57936091ea2a6867624f8fb60044cec29f1e5240

build:
  number: 1

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - aws-sdk-cpp
    - zlib
    - libboost-devel
    - libboost-headers
    - fmt
    - spdlog
  run:
    - aws-crt-cpp

tests:
  - script:
    - if: unix
      then: test -f $PREFIX/lib/libkhiopsdriver_file_s3${SHLIB_EXT}
      else:
        - if not exist %PREFIX%\Library\bin\libkhiopsdriver_file_s3.dll exit 1

about:
  homepage: https://khiops.org
  license: BSD-3-Clause-Clear
  license_file: LICENSE
  summary: Khiops driver to access files on AWS S3 storage
  description: The S3 driver plugin extends Khiops to enable processing of data files located on AWS S3 compatible storage

extra:
  recipe-maintainers:
    - popescu-v
    - sgouache
